name: main_draft1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  lottie: ^3.2.0
  intl: ^0.20.2
  http: ^1.3.0
  google_generative_ai: ^0.4.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
